# Generated by Django 4.1.3 on 2022-12-03 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('email_02', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('senha_02', models.CharField(max_length=20)),
                ('criaçao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
